<?php

namespace DP\ObserverBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DonneesMeteoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonneesMeteoRepository extends EntityRepository
{
}
